### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [Crusta/CrustaBrowser#11]
In addtabbutton.cpp

`              from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/tabview/addtabbutton.cpp:20:
/usr/include/qt/QtCore/qstring.h:1848:16: error: conflicting declaration of C function ‘QString operator+(QChar, const QStringRef&)’
 inline QString operator+(QChar s1, const QStringRef &s2)
                ^~~~~~~~
In file included from /usr/include/qt/QtCore/qstring.h:49,
                 from /usr/include/qt/QtCore/QString:1,
                 from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/utils/strings.h:22,
                 from /usr/include/string.h:431,
                 from /usr/include/qt/QtCore/qarraydata.h:44,
                 from /usr/include/qt/QtCore/qlist.h:46,
                 from /usr/include/qt/QtGui/qicon.h:45,
                 from /usr/include/qt/QtWidgets/qabstractbutton.h:44,
                 from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/tabview/addtabbutton.h:22,
                 from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/tabview/addtabbutton.cpp:20:
/usr/include/qt/QtCore/qbytearray.h:640:25: note: previous declaration ‘const QByteArray operator+(const QByteArray&, const QByteArray&)’
 inline const QByteArray operator+(const QByteArray &a1, const QByteArray &a2)
                         ^~~~~~~~
In file included from /usr/include/qt/QtCore/QString:1,
                 from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/utils/strings.h:22,
                 from /usr/include/string.h:431,
                 from /usr/include/qt/QtCore/qarraydata.h:44,
                 from /usr/include/qt/QtCore/qlist.h:46,
                 from /usr/include/qt/QtGui/qicon.h:45,
                 from /usr/include/qt/QtWidgets/qabstractbutton.h:44,
                 from /usr/include/qt/QtWidgets/qpushbutton.h:44,
                 from /usr/include/qt/QtWidgets/QPushButton:1,
                 from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/tabview/addtabbutton.h:22,
                 from /home/solaraquarion/build/crusta-browser-git/src/CrustaBrowser/src/tabview/addtabbutton.cpp:20:
/usr/include/qt/QtCore/qstring.h:1863:18: error: conflicting declaration of C function ‘QString&& QtPrivate::asString(QString&&)’
 inline QString &&asString(QString &&s)              { return std::move(s); }
                  ^~~~~~~~
/usr/include/qt/QtCore/qstring.h:1862:23: note: previous declaration ‘const QString& QtPrivate::asString(const QString&)’
 inline const QString &asString(const QString &s)    { return s; }
                       ^~~~~~~~
make[2]: *** [src/CMakeFiles/Crusta.dir/build.make:287: src/CMakeFiles/Crusta.dir/tabview/addtabbutton.cpp.o] Error 1
`

**Comment by tarptaeya** [comment]
can you please specify more details like your distro and qt version.

**Comment by SolarAquarion** [comment]
Qt 5.11.2 and ArchLinux

On Oct 28, 2018 2:39 PM, "Anmol Gautam" <notifications@github.com> wrote:

can you please specify more details like your distro and qt version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Crusta/CrustaBrowser/issues/11#issuecomment-433730327>,
or mute the thread

**Comment by tarptaeya** [comment]
Its fixed now and was because of missing QObject header. Thanks for reporting it
