### ISSUE TITLE
Can't change the two default search engines

### ISSUE THREAD

**Issue by ghost** [Crusta/CrustaBrowser#16]
Hello,
I don't want to use ecosia because of I don't want to support ads even if it's not tracked.

For ethical reasons I prefer to use other search engines like duckduckgo, and I can't change this.

**Comment by ghost** [comment]
And it's just not possible for me to have google as possible search engine, without the ability to remove it from the list!

**Comment by tarptaeya** [comment]
You can easily change your search engine as follows:
- Navigate to the engine you want to set as default (duckduck go in this case)
- Click on the notification icon next to the lock icon in the omnibar.
<img width="261" alt="Screenshot 2019-07-15 at 10 42 57 PM" src="https://user-images.githubusercontent.com/22481002/61235114-5531e180-a752-11e9-8037-4c6184182ed4.png">
- A prompt will ask you to add it to Crusta, click Add
<img width="318" alt="Screenshot 2019-07-15 at 10 44 33 PM" src="https://user-images.githubusercontent.com/22481002/61235115-55ca7800-a752-11e9-8ba7-ce2c882fd02a.png">
- It will then appear in the preferences from where you can set it as default.
<img width="612" alt="Screenshot 2019-07-15 at 10 48 06 PM" src="https://user-images.githubusercontent.com/22481002/61235227-a0e48b00-a752-11e9-9114-8ecbc800d96a.png">

**Comment by ghost** [comment]
Ok, but how can we remove google from search engines?

**Comment by ghost** [comment]
Thank you!

**Comment by tarptaeya** [comment]
> Ok, but how can we remove google from search engines?

The search engine list in the preferences is just the entry for each search engine added to crusta, currently there is no way to remove it.
