### ISSUE TITLE
Add a PKGBUILD file

### ISSUE THREAD

**Issue by dvorapa** [Crusta/CrustaBrowser#2]
When building and installing Crusta I got two errors:
- crusta binary could not be created, because there already is crusta directory (rename worked)
- PKGBUILD file is missing

I created some really basic one, but better would be to create proper one

(OS: Arch Linux, package manager: pamac)

**Comment by mmetak** [comment]
https://aur.archlinux.org/packages/crusta-browser-git/

**Comment by tarptaeya** [comment]
thanks @mmetak
